# vim: ts=2:sw=2

varSeps: "{}"
format: "{volume}"
plugins:
  volume:
    type: "volume"
    hight: "^fn(FontAwesome:size=9)^fn() {vol}%"
    medium: "^fn(FontAwesome:size=9)^fn() {vol}%"
    low: "^fn(FontAwesome:size=9)^fn() {vol}%"
    muted: "^fn(FontAwesome:size=9)^fg(#cc6666)^fg()^fn() {vol}%"
