# vim: ts=2:sw=2

# varSeps: "{}" # default
format: "{volume} wifi bat1 time layout gmail"
plugins:
  volume:
    path: "$GOPATH/src/github.com/pltanton/yags/plugins/volume/volume.so"
    sink: "/org/pulseaudio/core1/sink0"
    high: " {vol}%"
    medium: " {vol}%"
    low: " {vol}%"
    muted: " {vol}%"
  #bat1:
    #type: "battery"
    #name: "BAT1"
    #high: " {lvl}%"
    #medium: " {lvl}%"
    #low: " {lvl}%"
    #empty: " {lvl}%"
    #ac: " {lvl}%"
  #time:
    #type: "time"
    ## timeFormat: "Jan 2 15:04:05" # default
    ## pause: 1000 # default
  #layout:
    #type: "kbdd"
    #names: ["en", "ru"]
  #wifi:
    #type: "wifi"
    #connected: " {lvl}%"
    #disconnected: " N/A"
    #interface: "wlp4s0"
    #pause: 2000
  #gmail:
    #type: "maildir"
    #dir: "/home/anton/mail/gmail/INBOX/"
    #empty: " {new}"
    #filled: " {new}"
